### PR TITLE
Minor typo

### PR DESCRIPTION
**Pull request by ferboz**
Hi, 

I was checking xmodem code. I spotted a minor typo.
Thank you to share xmodem!

Best regards,
F.

### CODE REVIEW

**Comment by krishardy** [comment]
Thanks!  I'm happy with the patch but I want to look at the issue with Travis before I OK the merge.

Thanks!
-Kris

**Comment by krishardy** [comment]
I suspect that the Travis problem is a problem with apt-get talking to the Ubuntu repos during the setup for testing, but I'm grabbing an Ubuntu VM to do some isolated testing and make sure everything looks OK.  I hope to have an answer in a day or so.

**Comment by krishardy** [comment]
I've fixed the problem and will be merging in my PR with the Travis fix and then your PR.  Hang tight.

**Comment by ferboz** [comment]
Thank you

**Pull request merged**
